version: '3.5'
services:
  localstack-core-cloud:
    image: localstack/localstack:0.14.3
    ports:
      - '9330:9330'
    environment:
      - EDGE_PORT=9330
      - SERVICES=sqs,sns,s3
      - DEFAULT_REGION=us-east-1